export const WEAPON_DATA = {
  ak: {
    id: "ak",
    ammoType: "rifle",
    label: "AK",
    slot: "Digit1",
    damage: 34,
    fireInterval: 0.12,
    magSize: 10,
    reserveAmmo: 50,
    reloadDuration: 2.2,
    recoil: {
      pitchStep: 0.018,
      yawJitter: 0.006,
      pitchRecovery: 15,
      yawRecovery: 13,
    },
    audio: {
      reloadRate: 1,
      shootRate: 1,
    },
    ui: {
      crosshair: {
        moveSpread: 0.46,
        fireSpread: 0.52,
        reloadSpread: 0.9,
        smoothing: 14,
      },
    },
    viewModel: {
      rigModelPath: "./assets/models/FpsRig.glb",
      holderPosition: [0.18, -0.22, -0.32],
      recoilStrength: 0.035,
      recoilRecovery: 13,
      shootAnimationDuration: 0.22,
      muzzleFlashColor: 0xffe7b6,
      muzzleFlashDuration: 0.055,
      muzzleFlashIntensity: 3.4,
    },
  },
  smg: {
    id: "smg",
    ammoType: "light",
    label: "SMG",
    slot: "Digit2",
    damage: 24,
    fireInterval: 0.085,
    magSize: 24,
    reserveAmmo: 96,
    reloadDuration: 2.1,
    recoil: {
      pitchStep: 0.014,
      yawJitter: 0.005,
      pitchRecovery: 21,
      yawRecovery: 18,
    },
    audio: {
      reloadRate: 1.04,
      shootRate: 1.08,
    },
    ui: {
      crosshair: {
        moveSpread: 0.62,
        fireSpread: 0.7,
        reloadSpread: 0.75,
        smoothing: 16,
      },
    },
    viewModel: {
      rigModelPath: "./assets/models/FpsRig.glb",
      holderPosition: [0.19, -0.225, -0.325],
      recoilStrength: 0.026,
      recoilRecovery: 18,
      shootAnimationDuration: 0.18,
      muzzleFlashColor: 0xfff3cf,
      muzzleFlashDuration: 0.035,
      muzzleFlashIntensity: 2.5,
      weaponModelPath: "./assets/models/Submachine Gun.glb",
      weaponPosition: [-1.08, 0.84, 0.9],
      weaponQuaternion: [0, 0, 0, 1],
      weaponScale: [3.1, 3.1, 3.1],
    },
  },
  handgun: {
    id: "handgun",
    ammoType: "light",
    label: "Handgun",
    slot: "Digit3",
    damage: 46,
    fireInterval: 0.24,
    magSize: 12,
    reserveAmmo: 48,
    reloadDuration: 2.1,
    recoil: {
      pitchStep: 0.024,
      yawJitter: 0.009,
      pitchRecovery: 12,
      yawRecovery: 11,
    },
    audio: {
      reloadRate: 1,
      shootRate: 0.94,
    },
    ui: {
      crosshair: {
        moveSpread: 0.38,
        fireSpread: 0.74,
        reloadSpread: 0.95,
        smoothing: 11,
      },
    },
    viewModel: {
      rigModelPath: "./assets/models/Fps Rig_handgun.glb",
      holderPosition: [0.16, -0.18, -0.26],
      recoilStrength: 0.049,
      recoilRecovery: 10,
      shootAnimationDuration: 0.24,
      muzzleFlashColor: 0xffc27a,
      muzzleFlashDuration: 0.065,
      muzzleFlashIntensity: 4.2,
    },
  },
  knife: {
    id: "knife",
    ammoType: null,
    label: "Knife",
    slot: "Digit4",
    usesAmmo: false,
    damage: 70,
    range: 2.1,
    fireInterval: 0.52,
    magSize: 0,
    reserveAmmo: 0,
    reloadDuration: 0,
    recoil: {
      pitchStep: 0.008,
      yawJitter: 0.002,
      pitchRecovery: 18,
      yawRecovery: 16,
    },
    audio: {
      reloadRate: null,
      shootRate: null,
    },
    ui: {
      crosshair: {
        moveSpread: 0.28,
        fireSpread: 0.18,
        reloadSpread: 0,
        smoothing: 16,
      },
    },
    viewModel: {
      rigModelPath: "./fps_arms_knife_stab.glb",
      rigScale: [0.08, 0.08, 0.08],
      rigRotation: [0, Math.PI / 2, 0],
      holderPosition: [0.12, -0.2, -0.2],
      recoilStrength: 0.012,
      recoilRecovery: 18,
      shootAnimation: "KnifeStab",
      shootAnimationDuration: 0.38,
      idleAnimation: null,
      reloadAnimation: null,
      muzzleFlashColor: 0xffffff,
      muzzleFlashDuration: 0,
      muzzleFlashIntensity: 0,
    },
  },
};

export const WEAPON_ORDER = Object.values(WEAPON_DATA);
