export const GAME_CONFIG = {
  camera: {
    far: 1000,
    fov: 70,
    near: 0.1,
  },
  lighting: {
    directional: {
      color: 0xffffff,
      intensity: 2.5,
      position: [-5, 25, -1],
    },
    hemisphere: {
      groundColor: 0x00668d,
      intensity: 1.5,
      position: [2, 1, 1],
      skyColor: 0x8dc1de,
    },
  },
  player: {
    airAcceleration: 8,
    airDampingFactor: 0.1,
    floorDamping: 4,
    groundAcceleration: 25,
    jumpVelocity: 15,
    lookSensitivity: 0.002,
    oobY: -25,
    spawn: {
      end: [0, 1, 0],
      radius: 0.35,
      start: [0, 0.35, 0],
    },
    recoil: {
      pitchRecovery: 16,
      pitchStep: 0.018,
      yawJitter: 0.006,
      yawRecovery: 14,
    },
    presentation: {
      moveSpeedForFullBob: 8,
    },
    health: {
      max: 100,
    },
    sounds: {
      hurt: "./assets/sounds/player_hurt.mp3",
    },
  },
  targets: {
    items: [
      { position: [0, 1.1, -8], size: [0.75, 1.5, 0.45] },
      { position: [-2.5, 1.1, -12], size: [0.75, 1.5, 0.45] },
      { position: [2.75, 1.1, -15], size: [0.75, 1.5, 0.45] },
    ],
    maxHealth: 100,
    respawnDelay: 1.2,
    flinch: {
      scaleKick: 0.12,
      tiltKick: 0.12,
      recovery: 10,
    },
  },
  simulation: {
    gravity: 30,
    maxDeltaTime: 0.05,
    stepsPerFrame: 5,
  },
  world: {
    background: 0x88ccee,
    fogFar: 50,
    fogNear: 0,
    modelPath: "./examples/models/gltf/collision-world.glb",
  },
  weapon: {
    range: 200,
    damage: 34,
    fireInterval: 0.12,
    magSize: 10,
    reserveAmmo: 50,
    sounds: {
      reload: "./assets/sounds/reload.mp3",
      shoot: "./assets/sounds/laser.mp3",
    },
  },
  viewModel: {
    modelPath: "./assets/models/FpsRig.glb",
    holderPosition: [0.18, -0.22, -0.32],
    muzzleFlashDistance: 0.6,
    recoilRecovery: 14,
    recoilStrength: 0.035,
    rotation: [0, Math.PI / 2, 0],
    scale: [0.08, 0.08, 0.08],
    idleSway: {
      positionX: 0.012,
      positionY: 0.01,
      roll: 0.012,
      speed: 1.8,
      yaw: 0.01,
    },
    walkBob: {
      pitch: 0.018,
      positionX: 0.018,
      positionY: 0.016,
      roll: 0.028,
      speed: 9.5,
    },
  },
  ui: {
    crosshair: {
      baseScale: 1,
      fireScale: 0.4,
      moveScale: 0.5,
      reloadScale: 0.9,
      smoothing: 14,
    },
  },
  fx: {
    impactLifetime: 0.16,
    impactScale: 0.085,
    killImpactScale: 0.16,
    shardsPerImpact: 5,
  },
  pickups: {
    collectionRadius: 1.15,
    hoverHeight: 0.06,
    hoverSpeed: 4.8,
    spinSpeed: 2.6,
    ammo: {
      rifle: {
        modelPath: "./assets/models/7.62x39mm.glb",
        size: 0.22,
      },
      light: {
        modelPath: "./assets/models/9x19mm.glb",
        size: 0.16,
      },
    },
  },
  survival: {
    initialDelay: 2.5,
    intermissionDuration: 7,
    baseWaveCount: 4,
    perWaveIncrease: 2,
    spawnInterval: 0.65,
    navMesh: {
      modelPath: "./collision-world-navmesh.glb",
    },
    pressureRecovery: {
      maxPlayerDistance: 55,
      minSpawnDistance: 8,
      stuckDistanceEpsilon: 0.05,
      stuckTimeout: 6,
      stuckRecoveryDistance: 18,
    },
    routeAssist: {
      verticalThreshold: 1.35,
      nodes: [
        { id: "lower_left", position: [-8, 0, -6], links: ["lower_mid"] },
        { id: "lower_right", position: [8, 0, -6], links: ["lower_mid"] },
        { id: "lower_mid", position: [0, 0, -5.5], links: ["lower_left", "lower_right", "stair_bottom"] },
        { id: "stair_bottom", position: [0, 0, -8.2], links: ["lower_mid", "stair_mid"] },
        { id: "stair_mid", position: [0, 1.4, -10.5], links: ["stair_bottom", "stair_top"] },
        { id: "stair_top", position: [0, 2.8, -12.8], links: ["stair_mid", "upper_mid"] },
        { id: "upper_mid", position: [0, 2.8, -15.5], links: ["stair_top", "upper_left", "upper_right"] },
        { id: "upper_left", position: [-7.5, 2.8, -15.5], links: ["upper_mid"] },
        { id: "upper_right", position: [7.5, 2.8, -15.5], links: ["upper_mid"] },
      ],
    },
    spawnPoints: [
      [-8.5, 0.95, -5.5],
      [8.5, 0.95, -5.5],
      [-7.5, 0.95, -12.5],
      [7.5, 0.95, -12.5],
      [0, 0.95, -18],
      [-10.5, 0.95, -9],
      [10.5, 0.95, -9],
    ],
  },
  zombies: {
    walker: {
      attackType: "melee",
      attackCooldown: 0.95,
      attackDamage: 10,
      attackRange: 1.2,
      attackHeightTolerance: 1.1,
      height: 1.5,
      health: 55,
      modelPath: "./assets/models/Blue Demon.glb",
      radius: 0.45,
      scale: 0.27,
      speed: 3.15,
      score: 10,
      dropAmmoAmount: 6,
      dropAmmoType: "rifle",
      eyeHeight: 1.1,
      sightRange: 35,
      hearingRange: 20,
      memoryDuration: 6,
      animation: {
        death: "CharacterArmature|Death",
        hit: "CharacterArmature|HitReact",
        idle: "CharacterArmature|Idle",
        move: "CharacterArmature|Run",
        attack: "CharacterArmature|Punch",
      },
    },
    runner: {
      attackType: "ranged",
      attackCooldown: 1.25,
      attackDamage: 8,
      attackRange: 14,
      attackHeightTolerance: 2.4,
      height: 1.55,
      preferredRange: 8.5,
      retreatRange: 4.25,
      health: 38,
      modelPath: "./assets/models/Astronaut.glb",
      radius: 0.38,
      scale: 0.29,
      speed: 4.1,
      score: 18,
      dropAmmoAmount: 10,
      dropAmmoType: "light",
      eyeHeight: 1.08,
      sightRange: 40,
      hearingRange: 25,
      memoryDuration: 8,
      animation: {
        death: "CharacterArmature|Death",
        hit: "CharacterArmature|HitReact",
        idle: "CharacterArmature|Idle_Gun",
        move: "CharacterArmature|Run_Gun",
        attack: "CharacterArmature|Run_Gun_Shoot",
      },
    },
  },
};
